export default function Head() {
  return (
    <>
      <title>Dico</title>
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <meta name='description' content='Generated by create next app' />
      <meta property='og:image' content='/IMG_0318.JPG' key='ogimage' />
      <link rel='icon' href='/de-a-a-z.png' />
    </>
  );
}
